name: dart3x
description: A collection of extensions and reusable functions for dart and flutter packages
version: 0.0.1+1
homepage: https://www.github.com/osaxma/dart3x

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
